Repository PrimeDAO/prime-deals-dapp, pull requests merged in 2022-05, with the labels that each got.

#910 898 - Fix e2e tests after firebase auth
  src/main.ts
  src/services/EthereumServiceTesting.ts
Labels: Automated Tests

#982 973-Anchor links are scrolling behind the fixed header
  src/resources/elements/markdown/markdown.scss
Labels: Documentation

#1019 AU2: Updated webpack to serve static in build
  package-lock.json
  package.json
  webpack.config.js
Labels: Au2 Migration

#1021 AU2: All-Deals page
  package-lock.json
  package.json
  src/contribute/contribute.html
  src/contribute/contribute.scss
  src/contribute/contribute.ts
  src/deals/CounterPanel/CounterPanel.html
  src/deals/CounterPanel/CounterPanel.scss
  src/deals/CounterPanel/CounterPanel.ts
  src/deals/dealSummary/dealSummary.html
  src/deals/dealSummary/dealSummary.scss
  src/deals/dealSummary/dealSummary.ts
  src/deals/list/deals.html
  src/deals/list/deals.scss
  src/deals/list/deals.ts
  src/deals/timeLeft/timeLeft.html
  src/deals/timeLeft/timeLeft.scss
  src/deals/timeLeft/timeLeft.ts
  src/entities/DealDiscussions.ts
  src/entities/DealRegistrationTokenSwap.ts
  src/entities/DealTokenSwap.ts
  src/entities/IDealTypes.ts
  src/my-app.ts
  src/routes.ts
  src/services/ApplyDiffService.js
  src/services/AureliaHelperService.ts
  src/services/ConsoleLogService.ts
  src/services/DataSourceDealsTypes.ts
  src/services/DateService.ts
  src/services/DealService.ts
  src/services/FirebaseService.ts
  src/services/FirestoreDealsService.ts
  src/services/FirestoreService.ts
  src/services/FirestoreTypes.ts
  src/services/NumberService.ts
  src/services/SortService.ts
Labels: Au2 Migration

#1047 remove unused documents
  src/documentation/FAQ.md
  src/documentation/dealLaunch.md
  src/documentation/documents.json
  src/documentation/hostALaunch.md
  src/documentation/liquidLaunch.md
  src/documentation/overview.md
Labels: Refactor
